#!/usr/bin/env python3

from sys import argv

def usage(message):
    if message:
        print(message)
    print("Usage: {} <unclean_trace>".format(argv[0]))

def clean(f):
    n = 0
    c = 0
    k = 0
    print("n\tc\tk\taction\ttime_micros")
    for line in f.readlines():
        fields = line.strip().split("\t")
        if len(fields) < 2:
            continue
        if fields[0] == 'VALS':
            n = int(fields[1])
            c = int(fields[2])
            k = int(fields[3])
        elif len(fields) == 2 and fields[0] == 'GET' or fields[0] == 'PUT':
            try:
                print("{}\t{}\t{}\t{}\t{}".format(n, c, k, fields[0], int(fields[1])))
            except:
                continue

if __name__ == "__main__":
    if len(argv) != 2:
        usage("Must specify file!")
        exit(1)
    else:
        with open(argv[1]) as f:
            clean(f)
